"""add terms accepted at to user

Revision ID: 484acac465a6
Revises: e128d42368c9
Create Date: 2026-07-17 19:26:00.118006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484acac465a6'
down_revision = 'e128d42368c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted_at')

    # ### end Alembic commands ###
