"""recreate workout plans

Revision ID: 820157b24892
Revises: 11881209000b
Create Date: 2026-07-09 21:05:13.191391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820157b24892'
down_revision = '11881209000b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_plans_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_plans_user_id'))

    op.drop_table('workout_plans')
    # ### end Alembic commands ###
