"""add daily_tracker

Revision ID: e128d42368c9
Revises: 2b7497a20513
Create Date: 2026-07-12 18:40:48.853338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e128d42368c9'
down_revision = '2b7497a20513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    with op.batch_alter_table('daily_trackers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_trackers_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_trackers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_trackers_user_id'))

    op.drop_table('daily_trackers')
    # ### end Alembic commands ###
